apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sentinel-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vaibhav-2703/sentinel.git
    targetRevision: HEAD
    path: apps  # This points to the folder where we put deployment.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true      # If you delete a file in Git, delete it in the cluster
      selfHeal: true   # If someone manually deletes the pod, recreate it instantly